-- 1. Determine the Highest Purchase Amount Made by Each Salesperson on '2012-08-17'

SELECT salesman_id, MAX(purch_amt) AS purchase_amount
FROM ORDERS
WHERE ord_date = '2012-08-17'
GROUP BY salesman_id;

-- 2. Find the Highest Order Amount by Each Customer on a Particular Order Date, Filtered by Amount Above 2000.00

SELECT customer_id, ord_date, MAX(purch_amt) AS maximum_purchase_amount
FROM ORDERS
GROUP BY customer_id, ord_date
HAVING MAX(purch_amt) > 2000.00;

-- 3. Find the Maximum Order Amount in the Range 2000 - 6000 by Combination of Each Customer and Order Date

SELECT customer_id, ord_date, MAX(purch_amt) AS maximum_purchase_amount
FROM ORDERS
WHERE purch_amt BETWEEN 2000 AND 6000
GROUP BY customer_id, ord_date;

-- 4. Find the Maximum Order Amount for Specific Values by Combination of Each Customer and Order Date

SELECT customer_id, ord_date, MAX(purch_amt) AS maximum_purchase_amount
FROM ORDERS
WHERE purch_amt IN (2000, 3000, 5760, 6000)
GROUP BY customer_id, ord_date;

-- 5. Determine the Maximum Order Amount for Each Customer Within a Specific Customer ID Range

SELECT customer_id, MAX(purch_amt) AS maximum_purchase_amount
FROM ORDERS
WHERE customer_id BETWEEN 3002 AND 3007
GROUP BY customer_id;

-- 6. Find the Maximum Order Amount for Each Customer in a Specific ID Range, Filtered by Amount Higher Than 1000

SELECT customer_id, MAX(purch_amt) AS maximum_purchase_amount
FROM ORDERS
WHERE customer_id BETWEEN 3002 AND 3007
GROUP BY customer_id
HAVING MAX(purch_amt) > 1000;

-- 7. Determine the Maximum Order Amount Generated by Each Salesperson Within a Specific Salesperson ID Range

SELECT salesman_id, MAX(purch_amt) AS maximum_purchase_amount
FROM ORDERS
WHERE salesman_id BETWEEN 5003 AND 5008
GROUP BY salesman_id;

-- 8. Count All the Orders Generated on '2012-08-17'

SELECT COUNT(*) AS number_of_orders
FROM ORDERS
WHERE ord_date = '2012-08-17';

-- 9. Count the Number of Salespeople in Each City

SELECT city, COUNT(*) AS number_of_salespeople
FROM SALESMAN
GROUP BY city;

-- 10. Count the Number of Orders Based on Each Order Date and Salesperson

SELECT ord_date, salesman_id, COUNT(*) AS number_of_orders
FROM ORDERS
GROUP BY ord_date, salesman_id;